"""
Write Page - AI Review Generation
"""

import streamlit as st
import os
import sys
from datetime import datetime

# Add project root to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

from utils import (
    sidebar_settings,
    generate_ai_review,
    get_available_queries,
    error_display
)

# Page config
st.set_page_config(
    page_title="Write - Lit-Miner",
    page_icon="✍️",
    layout="wide"
)

# Render sidebar
config = sidebar_settings()

# Main content
st.title("✍️ AI Review Generation")
st.markdown("Generate comprehensive literature reviews using DeepSeek and RAG")

# Get available queries
available_queries = get_available_queries()

if not available_queries:
    st.warning("⚠️ No stored queries found. Please run a [Search](Search) first!")
    st.stop()

# Generation form
with st.form("write_form"):
    st.subheader("📚 Select Data Source")
    
    # Query selection
    use_current = st.checkbox(
        "Use current session query",
        value="current_query" in st.session_state,
        disabled="current_query" not in st.session_state
    )
    
    if use_current and "current_query" in st.session_state:
        query = st.session_state["current_query"]
        st.info(f"📌 Using: **{query}**")
    else:
        query = st.selectbox(
            "Select from stored queries",
            available_queries,
            help="Choose a previously completed search"
        )
    
    st.divider()
    
    # Topic input
    st.subheader("📝 Review Settings")
    
    topic = st.text_input(
        "Review Topic (optional)",
        placeholder="Leave blank for auto-generation from papers",
        help="Custom topic for the review. If empty, will be auto-generated by AI."
    )
    
    n_results = st.slider(
        "Number of Papers to Include",
        min_value=5,
        max_value=50,
        value=20,
        step=5,
        help="How many papers to retrieve from the database for review generation"
    )
    
    submitted = st.form_submit_button("✍️ Generate Review", type="primary")

# Handle generation
if submitted:
    if not query:
        st.warning("⚠️ Please select a query")
    else:
        # Log container
        log_container = st.empty()
        logs = []
        
        def log_callback(message: str):
            """Callback to capture logs"""
            logs.append(f"[{datetime.now().strftime('%H:%M:%S')}] {message}")
            log_container.code("\n".join(logs), language="log")
        
        # Progress
        progress = st.progress(0, text="Starting review generation...")
        
        try:
            st.info("✍️ Generating AI-powered review...")
            progress.progress(20, text="Loading database...")
            
            result = generate_ai_review(
                query=query,
                topic=topic if topic.strip() else None,
                n_results=n_results,
                log_callback=log_callback
            )
            
            progress.progress(100, text="Complete!")
            
            # Store in session state
            st.session_state["generated_review"] = result["markdown"]
            st.session_state["review_topic"] = result["topic"]
            st.session_state["review_query"] = query
            
            # Success message
            st.success(f"✅ Review generated successfully!")
            st.info(f"📌 Topic: **{result['topic']}**")
            
            progress.empty()
            
        except Exception as e:
            progress.empty()
            error_display(e)

# Display generated review
if "generated_review" in st.session_state:
    st.divider()
    st.header("📝 Generated Review")
    
    # Metadata
    col1, col2 = st.columns(2)
    with col1:
        st.caption(f"**Topic:** {st.session_state.get('review_topic', 'N/A')}")
    with col2:
        st.caption(f"**Source Query:** {st.session_state.get('review_query', 'N/A')}")
    
    # Review content
    st.markdown("---")
    
    # Display in expander for better UX
    with st.expander("📖 View Full Review", expanded=True):
        st.markdown(st.session_state["generated_review"])
    
    # Export options
    st.divider()
    st.subheader("💾 Export")
    
    col1, col2 = st.columns(2)
    
    with col1:
        # Download as Markdown
        filename = f"review_{st.session_state.get('review_topic', 'untitled').replace(' ', '_')[:30]}.md"
        st.download_button(
            "📥 Download Markdown",
            data=st.session_state["generated_review"],
            file_name=filename,
            mime="text/markdown"
        )
    
    with col2:
        # Copy to clipboard (requires user action)
        if st.button("📋 Copy to Clipboard"):
            st.code(st.session_state["generated_review"], language="markdown")
            st.info("👆 Select and copy the text above")

else:
    st.info("👆 Configure settings above and click 'Generate Review' to get started")

# Tips
st.divider()
st.markdown("""
### 💡 Tips
- **Auto-topic generation** works best with 15-30 papers
- **Custom topics** should be specific (e.g., "Role of bone substitutes in socket preservation")
- Reviews typically take 30-60 seconds to generate
- Generated reviews are stored in session - download before refreshing!
""")
